language: python

python:
  - 3.6

before_install:
  - gem update --system
  - gem install sass --version "=3.5.3"

install:
  - pip install -r requirements.txt
  - pip install '.[test,website]'
  - whotracksme --help

script:
  - pytest
  - whotracksme website

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _site
    target_branch: gh-pages
    on:
      branch: master
#   - deploy:
#     provider: pypi
#     distributions: "sdist bdist_wheel"
#     user: "Your username"
#     password:
#       secure: "Your encrypted password"
#     on:
#       tags: true
#   - deploy:
#     provider: s3
#     access_key_id: "YOUR AWS ACCESS KEY"
#     secret_access_key: "YOUR AWS SECRET KEY"
#     bucket: "S3 Bucket"
#     skip_cleanup: true
#     region: "Bucket region"
#     before_deploy:
#       - echo "Run some script"
#     on:
#       branch: production # Only deploys to S3 from the `production` branch
