
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install sass
        run: |
          sudo apt-get update
          sudo apt-get install --yes ruby-sass build-essential
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e '.[dev]'
          whotracksme --help
      - name: Run tests
        run: |
          pytest
      - name: Build Site
        run: |
          whotracksme website
          rm -rf whotracksme/ # cleanup disk space for deploy in next step
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
